/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedConectarRouteImport } from './routes/_authed/conectar'
import { Route as AuthedFunilRouteImport } from './routes/_authed/funil'
import { Route as AuthedLeadsRouteImport } from './routes/_authed/leads'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedConectarRoute = AuthedConectarRouteImport.update({
  id: '/conectar',
  path: '/conectar',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFunilRoute = AuthedFunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLeadsRoute = AuthedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/conectar': typeof AuthedConectarRoute
  '/funil': typeof AuthedFunilRoute
  '/leads': typeof AuthedLeadsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/conectar': typeof AuthedConectarRoute
  '/funil': typeof AuthedFunilRoute
  '/leads': typeof AuthedLeadsRoute
  '/': typeof AuthedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/conectar': typeof AuthedConectarRoute
  '/_authed/funil': typeof AuthedFunilRoute
  '/_authed/leads': typeof AuthedLeadsRoute
  '/_authed/': typeof AuthedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/conectar' | '/funil' | '/leads'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/conectar' | '/funil' | '/leads' | '/'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/conectar'
    | '/_authed/funil'
    | '/_authed/leads'
    | '/_authed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/conectar': {
      id: '/_authed/conectar'
      path: '/conectar'
      fullPath: '/conectar'
      preLoaderRoute: typeof AuthedConectarRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/funil': {
      id: '/_authed/funil'
      path: '/funil'
      fullPath: '/funil'
      preLoaderRoute: typeof AuthedFunilRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/leads': {
      id: '/_authed/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthedLeadsRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedConectarRoute: typeof AuthedConectarRoute
  AuthedFunilRoute: typeof AuthedFunilRoute
  AuthedLeadsRoute: typeof AuthedLeadsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedConectarRoute: AuthedConectarRoute,
  AuthedFunilRoute: AuthedFunilRoute,
  AuthedLeadsRoute: AuthedLeadsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
