/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedCalendarioRouteImport } from './routes/_authed/calendario'
import { Route as AuthedClienteRouteImport } from './routes/_authed/cliente'
import { Route as AuthedClientesRouteImport } from './routes/_authed/clientes'
import { Route as AuthedConectarRouteImport } from './routes/_authed/conectar'
import { Route as AuthedConfiguracoesRouteImport } from './routes/_authed/configuracoes'
import { Route as AuthedEscolherClienteRouteImport } from './routes/_authed/escolher-cliente'
import { Route as AuthedFunilRouteImport } from './routes/_authed/funil'
import { Route as AuthedLeadsRouteImport } from './routes/_authed/leads'
import { Route as AuthedNotificacoesRouteImport } from './routes/_authed/notificacoes'
import { Route as AuthedPerfilRouteImport } from './routes/_authed/perfil'
import { Route as AuthedPostagensRouteImport } from './routes/_authed/postagens'
import { Route as AuthedClientesClienteIdRouteImport } from './routes/_authed/clientes_.$clienteId'
import { Route as AuthedEventosIndexRouteImport } from './routes/_authed/eventos/index'
import { Route as AuthedEventosEventoIdRouteImport } from './routes/_authed/eventos/$eventoId'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCalendarioRoute = AuthedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedClienteRoute = AuthedClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedClientesRoute = AuthedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedConectarRoute = AuthedConectarRouteImport.update({
  id: '/conectar',
  path: '/conectar',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedConfiguracoesRoute = AuthedConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEscolherClienteRoute = AuthedEscolherClienteRouteImport.update({
  id: '/escolher-cliente',
  path: '/escolher-cliente',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFunilRoute = AuthedFunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLeadsRoute = AuthedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNotificacoesRoute = AuthedNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPerfilRoute = AuthedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPostagensRoute = AuthedPostagensRouteImport.update({
  id: '/postagens',
  path: '/postagens',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedClientesClienteIdRoute = AuthedClientesClienteIdRouteImport.update({
  id: '/clientes_/$clienteId',
  path: '/clientes/$clienteId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEventosIndexRoute = AuthedEventosIndexRouteImport.update({
  id: '/eventos/',
  path: '/eventos/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEventosEventoIdRoute = AuthedEventosEventoIdRouteImport.update({
  id: '/eventos/$eventoId',
  path: '/eventos/$eventoId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/calendario': typeof AuthedCalendarioRoute
  '/cliente': typeof AuthedClienteRoute
  '/clientes': typeof AuthedClientesRoute
  '/conectar': typeof AuthedConectarRoute
  '/configuracoes': typeof AuthedConfiguracoesRoute
  '/escolher-cliente': typeof AuthedEscolherClienteRoute
  '/funil': typeof AuthedFunilRoute
  '/leads': typeof AuthedLeadsRoute
  '/notificacoes': typeof AuthedNotificacoesRoute
  '/perfil': typeof AuthedPerfilRoute
  '/postagens': typeof AuthedPostagensRoute
  '/clientes/$clienteId': typeof AuthedClientesClienteIdRoute
  '/eventos/$eventoId': typeof AuthedEventosEventoIdRoute
  '/eventos/': typeof AuthedEventosIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/calendario': typeof AuthedCalendarioRoute
  '/cliente': typeof AuthedClienteRoute
  '/clientes': typeof AuthedClientesRoute
  '/conectar': typeof AuthedConectarRoute
  '/configuracoes': typeof AuthedConfiguracoesRoute
  '/escolher-cliente': typeof AuthedEscolherClienteRoute
  '/funil': typeof AuthedFunilRoute
  '/leads': typeof AuthedLeadsRoute
  '/notificacoes': typeof AuthedNotificacoesRoute
  '/perfil': typeof AuthedPerfilRoute
  '/postagens': typeof AuthedPostagensRoute
  '/': typeof AuthedIndexRoute
  '/clientes/$clienteId': typeof AuthedClientesClienteIdRoute
  '/eventos/$eventoId': typeof AuthedEventosEventoIdRoute
  '/eventos': typeof AuthedEventosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/calendario': typeof AuthedCalendarioRoute
  '/_authed/cliente': typeof AuthedClienteRoute
  '/_authed/clientes': typeof AuthedClientesRoute
  '/_authed/conectar': typeof AuthedConectarRoute
  '/_authed/configuracoes': typeof AuthedConfiguracoesRoute
  '/_authed/escolher-cliente': typeof AuthedEscolherClienteRoute
  '/_authed/funil': typeof AuthedFunilRoute
  '/_authed/leads': typeof AuthedLeadsRoute
  '/_authed/notificacoes': typeof AuthedNotificacoesRoute
  '/_authed/perfil': typeof AuthedPerfilRoute
  '/_authed/postagens': typeof AuthedPostagensRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/clientes_/$clienteId': typeof AuthedClientesClienteIdRoute
  '/_authed/eventos/$eventoId': typeof AuthedEventosEventoIdRoute
  '/_authed/eventos/': typeof AuthedEventosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/calendario'
    | '/cliente'
    | '/clientes'
    | '/conectar'
    | '/configuracoes'
    | '/escolher-cliente'
    | '/funil'
    | '/leads'
    | '/notificacoes'
    | '/perfil'
    | '/postagens'
    | '/clientes/$clienteId'
    | '/eventos/$eventoId'
    | '/eventos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/calendario'
    | '/cliente'
    | '/clientes'
    | '/conectar'
    | '/configuracoes'
    | '/escolher-cliente'
    | '/funil'
    | '/leads'
    | '/notificacoes'
    | '/perfil'
    | '/postagens'
    | '/'
    | '/clientes/$clienteId'
    | '/eventos/$eventoId'
    | '/eventos'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/calendario'
    | '/_authed/cliente'
    | '/_authed/clientes'
    | '/_authed/conectar'
    | '/_authed/configuracoes'
    | '/_authed/escolher-cliente'
    | '/_authed/funil'
    | '/_authed/leads'
    | '/_authed/notificacoes'
    | '/_authed/perfil'
    | '/_authed/postagens'
    | '/_authed/'
    | '/_authed/clientes_/$clienteId'
    | '/_authed/eventos/$eventoId'
    | '/_authed/eventos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/calendario': {
      id: '/_authed/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthedCalendarioRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/cliente': {
      id: '/_authed/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof AuthedClienteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/clientes': {
      id: '/_authed/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthedClientesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/conectar': {
      id: '/_authed/conectar'
      path: '/conectar'
      fullPath: '/conectar'
      preLoaderRoute: typeof AuthedConectarRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/configuracoes': {
      id: '/_authed/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthedConfiguracoesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/escolher-cliente': {
      id: '/_authed/escolher-cliente'
      path: '/escolher-cliente'
      fullPath: '/escolher-cliente'
      preLoaderRoute: typeof AuthedEscolherClienteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/funil': {
      id: '/_authed/funil'
      path: '/funil'
      fullPath: '/funil'
      preLoaderRoute: typeof AuthedFunilRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/leads': {
      id: '/_authed/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthedLeadsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/notificacoes': {
      id: '/_authed/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthedNotificacoesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/perfil': {
      id: '/_authed/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthedPerfilRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/postagens': {
      id: '/_authed/postagens'
      path: '/postagens'
      fullPath: '/postagens'
      preLoaderRoute: typeof AuthedPostagensRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/clientes_/$clienteId': {
      id: '/_authed/clientes_/$clienteId'
      path: '/clientes/$clienteId'
      fullPath: '/clientes/$clienteId'
      preLoaderRoute: typeof AuthedClientesClienteIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/eventos/': {
      id: '/_authed/eventos/'
      path: '/eventos'
      fullPath: '/eventos/'
      preLoaderRoute: typeof AuthedEventosIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/eventos/$eventoId': {
      id: '/_authed/eventos/$eventoId'
      path: '/eventos/$eventoId'
      fullPath: '/eventos/$eventoId'
      preLoaderRoute: typeof AuthedEventosEventoIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedCalendarioRoute: typeof AuthedCalendarioRoute
  AuthedClienteRoute: typeof AuthedClienteRoute
  AuthedClientesRoute: typeof AuthedClientesRoute
  AuthedConectarRoute: typeof AuthedConectarRoute
  AuthedConfiguracoesRoute: typeof AuthedConfiguracoesRoute
  AuthedEscolherClienteRoute: typeof AuthedEscolherClienteRoute
  AuthedFunilRoute: typeof AuthedFunilRoute
  AuthedLeadsRoute: typeof AuthedLeadsRoute
  AuthedNotificacoesRoute: typeof AuthedNotificacoesRoute
  AuthedPerfilRoute: typeof AuthedPerfilRoute
  AuthedPostagensRoute: typeof AuthedPostagensRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedClientesClienteIdRoute: typeof AuthedClientesClienteIdRoute
  AuthedEventosEventoIdRoute: typeof AuthedEventosEventoIdRoute
  AuthedEventosIndexRoute: typeof AuthedEventosIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCalendarioRoute: AuthedCalendarioRoute,
  AuthedClienteRoute: AuthedClienteRoute,
  AuthedClientesRoute: AuthedClientesRoute,
  AuthedConectarRoute: AuthedConectarRoute,
  AuthedConfiguracoesRoute: AuthedConfiguracoesRoute,
  AuthedEscolherClienteRoute: AuthedEscolherClienteRoute,
  AuthedFunilRoute: AuthedFunilRoute,
  AuthedLeadsRoute: AuthedLeadsRoute,
  AuthedNotificacoesRoute: AuthedNotificacoesRoute,
  AuthedPerfilRoute: AuthedPerfilRoute,
  AuthedPostagensRoute: AuthedPostagensRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedClientesClienteIdRoute: AuthedClientesClienteIdRoute,
  AuthedEventosEventoIdRoute: AuthedEventosEventoIdRoute,
  AuthedEventosIndexRoute: AuthedEventosIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
